In [10]:
import numpy as np
from scipy.signal import convolve2d

# Ejercicio 1

In [2]:
def convol_1d(xs, ys):
    print("Convolve 1d:", xs, ys)
    starting_point = int(np.trunc(len(ys)/2))
    padded_xs = np.pad(xs, (starting_point,starting_point), 'constant', constant_values=(0,0))
    ending_point = len(padded_xs) - starting_point
    ys_reversed = np.flip(ys)
    res = np.zeros(len(padded_xs))
    for pos in range(starting_point, ending_point):
        accum = 0
        for y_index in range(len(ys_reversed)):
            accum += (ys_reversed[y_index] * padded_xs[pos + y_index - starting_point])
        res[pos] = accum
    return res.astype(np.int64)

In [11]:
xs1 = np.array([0, 1, 0, 0, 0, 0])
h1 = np.array([0, 2, 1, 0, 0])

print(convol_1d(xs1, h1))
print(np.convolve(xs1, h1, mode='full'))

Convolve 1d: [0 1 0 0 0 0] [0 2 1 0 0]
[0 0 2 1 0 0 0 0 0 0]
[0 0 2 1 0 0 0 0 0 0]


In [4]:
xs2 = np.array([0, 0, 1, 0, 0, 0])
h2 = h1

print(convol_1d(xs2, h2))
print(np.convolve(xs2, h2, mode='full'))

Convolve 1d: [0 0 1 0 0 0] [0 2 1 0 0]
[0 0 0 2 1 0 0 0 0 0]
[0 0 0 2 1 0 0 0 0 0]


In [5]:
xs3 = np.array([0, 2, -1, 0, 0, 0])
h3 = np.array([0, -1, 2, 1, 0])

print(convol_1d(xs3, h3))
print(np.convolve(xs3, h3, mode='full'))

Convolve 1d: [ 0  2 -1  0  0  0] [ 0 -1  2  1  0]
[ 0  0 -2  5  0 -1  0  0  0  0]
[ 0  0 -2  5  0 -1  0  0  0  0]


In [6]:
# xs3 = np.array([0, 2, -1, 0, 0, 0])
# h3 = np.array([0, -1, 2, 1, 0])

# print(convol_1d(xs3, h3))
# print(np.convolve(xs3, h3, mode='full'))

# Ejercicio 2

In [9]:
I = np.array([[1,4,1],
              [2,5,3]])

convi = np.array([
    [0,-1,1],
    [-1,4,-1],
    [0,-1,0]
])

convii = np.array([
    [1,2,3]
])

conviii = np.array([
    [-2],
    [3],
    [-1]
])

print(convolve2d(I, convi))
print(convolve2d(I, convii))
print(convolve2d(I, conviii))

[[ 0 -1 -3  3  1]
 [-1 -2 11  2  2]
 [-2  2 11  6 -3]
 [ 0 -2 -5 -3  0]]
[[ 1  6 12 14  3]
 [ 2  9 19 21  9]]
[[-2 -8 -2]
 [-1  2 -3]
 [ 5 11  8]
 [-2 -5 -3]]


b) 
Dado el algoritmo que se nos da para hacer la convolucion I * H matrices de (M1,N1) y (M2,N2) respectivamente, se puede ver que a la matriz resultante es del mismo tamaño que I con un extra de padding necesario para centrar H en cada punto de I.
Por ejemplo, para centrar H en la posicion (0,0) de I, es necesario agregarle M2/2 -0.5 filas y N2/2-0.5 columnas (Con M2 y N2 impares). de esta forma se le agrega en 2*(M2/2-0.5) = M2-1  filas y N2-1 columnas, con lo cual la matriz resultante termina siendo de dimensión (M1+M2-1, N1+N2-1)

In [73]:
def convolve2d(I, H, fun=np.inner):
    sp = (int(H.shape[0]/2 - 0.5), int(H.shape[1]/2 - 0.5))
    I = np.pad(I, ((sp[0],sp[0]), (sp[1],sp[1])), 'constant', constant_values=(0,0))
    H = np.flip(H)
    ep = (I.shape[0]-1-sp[0], I.shape[1]-1-sp[1])
    
    result_matrix = np.zeros(I.shape)
    for row in range(sp[0], ep[0]+1):
        for col in range(sp[1], ep[1]+1):
            sub_matrix_row_start = row-sp[0]
            sub_matrix_row_end = sub_matrix_row_start + H.shape[0]
            sub_matrix_col_start = col-sp[1]
            sub_matrix_col_end = sub_matrix_col_start + H.shape[1]
            
            sub_matrix = I[sub_matrix_row_start:sub_matrix_row_end, sub_matrix_col_start:sub_matrix_col_end]
            fun(sub_matrix)

In [74]:
convolve2d(convi, convii)

[[ 0  0 -1]]
[[ 0 -1  1]]
[[-1  1  0]]
[[ 0 -1  4]]
[[-1  4 -1]]
[[ 4 -1  0]]
[[ 0  0 -1]]
[[ 0 -1  0]]
[[-1  0  0]]
